blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    # path(
    #     '',
    #     views.PostListView.as_view(),
    #     name='post_list'
    # ),
    path(
        '',
        views.post_list,
        name='post_list'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>',
        views.post_detail,
        name='post_detail'
    ),
    path(
        '<int:post_id>/share/',
        views.post_share,
        name='post_share'
    ),
    path(
        'tag/<slug:tag_slug>',
        views.post_list,
        name='post_list_by_tag'
    )
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, blank=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    body = models.TextField(blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()      # Менеджер по умолчанию.
    published = PublishedManager()  # Наш новый менеджер.
    tags = TaggableManager()    # tags

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ]
        )

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, blank=True)
    email = models.EmailField(blank=True)
    body = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comments by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment
from django.forms import ModelForm


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label='Name')
    email = forms.EmailField(label='Email from')
    to = forms.EmailField(label='Email to')
    comments = forms.CharField(required=False, widget=forms.Textarea, label='Comments')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from taggit.models import Tag
from django.db.models import Count


# Create your views here.
# Show posts list
def post_list(request, tag_slug=None):
    object_list = Post.published.all()

    # Tags
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # Pagination
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'blog/post/list.html',
        {
            'page': page,
            'posts': posts,
            'tag': tag,
        }
    )


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


# Show post detail
def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    # List active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # User sent comment
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment without saving in BD
            new_comment = comment_form.save(commit=False)
            # Link a comment to the current article
            new_comment.post = post
            # Save comment to BD
            new_comment.save()
    else:
        comment_form = CommentForm()

    # Similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published\
        .filter(tags__in=post_tags_ids)\
        .exclude(id=post.id)
    similar_posts = similar_posts\
        .annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'similar_posts': similar_posts,
        }
    )


# Share form
def post_share(request, post_id):
    # Get post on id
    post = get_object_or_404(
        Post,
        id=post_id,
        status='published',
    )
    sent = False
    if request.method == 'POST':
        # form arrived to save
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # validation is True
            cd = form.cleaned_data
            # sending
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin0@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        }
    )

templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>

        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}

        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>

    <p class="date">Published {{ post.publish|date:'d M Y' }} by {{ post.author }}</p>
    {{ post.body|linebreaks }}

    {#  Show tags  #}
    {% if post.tags.all %}
        <p class="tags">Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% endif %}
    {#  Show tags end  #}

    {#  Share  #}
    <p>
        <a href="{% url "blog:post_share" post.id %}">Share this post</a>
    </p>
    {#  Share end  #}

    {#  Show similar posts  #}
    {% if similar_posts %}
        <hr>
        <h3>Similar posts</h3>
        {% for post in similar_posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
        {% endfor %}
    {% endif %}
    {#  Show similar posts end  #}

    {#  Show comment count  #}
    <hr>
    {% with comments.count as tottal_comments %}
         <h3>{{ tottal_comments }} comment{{ tottal_comments|pluralize }}</h3>
    {% endwith %}
    {#  Show comment count end  #}

    {#  Show comments  #}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are not comments yet</p>
    {% endfor %}
    {#  Show comments end  #}

    {#  Show comments form  #}
    {% if new_comment %}
        <h2>Your comment has been added</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p>
                <input type="submit" value="Add comment">
            </p>
        </form>
    {% endif %}
    {#  Show comments form end  #}
{% endblock %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}
    My blog
{% endblock %}
{% block content %}
    <h1>My Blog</h1>

    {#  Tags  #}
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {#  Tags end  #}

    {#  Post  #}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="date">Published {{ post.publish|date:'d M Y' }} by {{ post.author }}</p>
        {{ post.body|truncatewords:30|linebreaks }}
        {% if post.tags.all %}
        <p class="tags">Tags: 
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        {% endif %}
    {% endfor %}
    {#  Post end  #}

    {#  Pagination  #}
    {% include 'pagination.html' with page=posts %}
    {#  Pagination end  #}

{% endblock %}

templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}
    Share a post
{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Email successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>